# Generated by Django 5.2.8 on 2026-04-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, verbose_name="个人介绍"),
        ),
    ]
