# Generated by Django 5.2.8 on 2026-04-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_agent_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="公开到广场"),
        ),
    ]
