# Generated by Django 5.2.8 on 2026-04-13 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_started_by(apps, schema_editor):
    Conversation = apps.get_model("conversations", "Conversation")
    for c in Conversation.objects.filter(started_by__isnull=True).iterator():
        owner_id = getattr(c.agent, "owner_id", None)
        if owner_id:
            c.started_by_id = owner_id
            c.save(update_fields=["started_by_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="started_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="started_conversations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="发起用户",
            ),
        ),
        migrations.RunPython(backfill_started_by, migrations.RunPython.noop),
    ]
